name: 'setup-mstest'
description: 'Helps set up MSTest into PATH for later usage.'
author: ''
branding:
  color: purple
  icon: terminal
inputs:
  vswhere-path:
    required: false
    description: 'Folder location of where vswhere.exe is located if a self-hosted agent'
  vs-version:
    description: 'Version of Visual Studio to search; defaults to latest if not specified'
    required: false
outputs:
  mstestPath:
    description: 'The resulting location of mstest for your inputs'

runs:
  using: 'node12'
  main: 'dist/index.js'
